// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace BitirmeTeziML.Model
{
    public class ModelInput
    {
        [ColumnName("sentence"), LoadColumn(0)]
        public string Sentence { get; set; }


        [ColumnName("emotion"), LoadColumn(1)]
        public string Emotion { get; set; }


    }
}
